<a href="https://colab.research.google.com/github/Icacorpuz/ACTIVITY/blob/main/Untitled10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

In [23]:
df_bike = pd.read_csv('https://raw.githubusercontent.com/Icacorpuz/ACTIVITY/main/RailsToTrails_National%20Count%20Data_week.csv')

In [24]:
df_bike.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
0,Week 1,12/30/2020,68957.0,93654.0,36%
1,Week 2,1/6/2020,34778.0,46964.0,35%
2,Week 3,1/13/2020,32065.0,38302.0,19%
3,Week 4,1/20/2020,35016.0,41506.0,19%
4,Week 5,1/27/2020,33627.0,46335.0,38%

In [31]:
df_data = (df_bike [df_bike['Week of'] >= '31-July'])
df_data.head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%

In [32]:
df_fil = df_bike['Week of'] >='31-July'
df_fil.head()

0    False
1    False
2    False
3    False
4    False
Name: Week of, dtype: bool

In [34]:
df_bike.loc[df_fil].head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%

In [36]:
df_bike.loc[df_fil, :].head()

,Timeframe,Week of,2019 counts (14 counters),2020 counts (14 counters),Change 2019-2020
14,Week 15,4/6/2020,83893.0,107420.0,28%
15,Week 16,4/13/2020,71677.0,122291.0,71%
16,Week 17,4/20/2020,87834.0,106246.0,21%
17,Week 18,4/27/2020,88284.0,109459.0,24%
18,Week 19,5/4/2020,94980.0,109391.0,15%